# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ICBM.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ICBM.proto',
  package='ICBM_PAYLOAD',
  serialized_pb=_b('\n\nICBM.proto\x12\x0cICBM_PAYLOAD\"\xf3\x01\n\x03Log\x12\x0e\n\x06server\x18\x01 \x02(\t\x12\x0c\n\x04time\x18\x02 \x02(\t\x12&\n\x05level\x18\x03 \x02(\x0e\x32\x17.ICBM_PAYLOAD.Log.Level\x12\x0f\n\x07\x63ontext\x18\x04 \x02(\t\x12\x10\n\x08\x66unction\x18\x05 \x02(\t\x12\x0c\n\x04line\x18\x06 \x02(\x05\x12\x0e\n\x06module\x18\x07 \x02(\t\x12\x0f\n\x07message\x18\x08 \x02(\t\x12\x10\n\x08\x65xc_info\x18\t \x01(\t\"B\n\x05Level\x12\t\n\x05\x44\x45\x42UG\x10\n\x12\x08\n\x04INFO\x10\x14\x12\x0b\n\x07WARNING\x10\x1e\x12\t\n\x05\x45RROR\x10(\x12\x0c\n\x08\x43RITICAL\x10\x32')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_LOG_LEVEL = _descriptor.EnumDescriptor(
  name='Level',
  full_name='ICBM_PAYLOAD.Log.Level',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=0, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=1, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=2, number=30,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=3, number=40,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL', index=4, number=50,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=206,
  serialized_end=272,
)
_sym_db.RegisterEnumDescriptor(_LOG_LEVEL)


_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='ICBM_PAYLOAD.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server', full_name='ICBM_PAYLOAD.Log.server', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='ICBM_PAYLOAD.Log.time', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='ICBM_PAYLOAD.Log.level', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context', full_name='ICBM_PAYLOAD.Log.context', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='function', full_name='ICBM_PAYLOAD.Log.function', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='line', full_name='ICBM_PAYLOAD.Log.line', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module', full_name='ICBM_PAYLOAD.Log.module', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='ICBM_PAYLOAD.Log.message', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exc_info', full_name='ICBM_PAYLOAD.Log.exc_info', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOG_LEVEL,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=272,
)

_LOG.fields_by_name['level'].enum_type = _LOG_LEVEL
_LOG_LEVEL.containing_type = _LOG
DESCRIPTOR.message_types_by_name['Log'] = _LOG

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), dict(
  DESCRIPTOR = _LOG,
  __module__ = 'ICBM_pb2'
  # @@protoc_insertion_point(class_scope:ICBM_PAYLOAD.Log)
  ))
_sym_db.RegisterMessage(Log)


# @@protoc_insertion_point(module_scope)
